### ISSUE TITLE
MoccaFaux does not inhibit power management

### ISSUE THREAD

**Issue by Ahmed-E-86** [mzuther/MoccaFaux#1]
### Steps that I followed to produce the issue:

1- I opened `moccafaux-1.4.1.jar` using `OpenJDK Java 11 Runtime` and the tray-icon of the application appeared.

2- I opened Clementine and waited for 60 seconds, and the icon of the application changed to green  (`dpms -> Active, sleep -> idle`)

3- I waited 5 minutes and the screen turned off, and my laptop went to sleep after 10 minutes.

**config.edn**

```
{
   :settings {
      :add-traybar-icon true
      :probing-interval 60
   }

   :tasks {
      :sleep {
         :active { :message "allow computer to save energy"
                   :command "xautolock -time 10 -locker 'systemctl suspend' -detectsleep"
                   :fork    true }

         :idle   { :message "keep computer awake"
                   :command "xautolock -exit"
                   :fork    false } }

      :dpms {
         :active { :message "allow screen to save energy"
                   :command "xset dpms 0 600 900"
                   :fork    false }

         :idle   { :message "keep screen awake"
                   :command "xset -dpms"
                   :fork    false } }
   }

   :watches {
      :important-processes {
         :enabled true
         :command "pgrep -af '^dpkg\\b|^pacman\\b|^dar\\s|\\bgparted\\b|^k3b\\b|^/\\S*rsync\\b|^ssh\\s|^sshd:.*\\[priv\\]|^unison\\S*|\\bgsmartcontrol\\b|^ffmpeg\\s'"
         :tasks   { :sleep true } }

      :audio {
         :enabled true
         :command "pgrep -l '^(clementine|deadbeef\\S+|quodlibet)$'"
         :tasks   { :sleep true } }

      :pulseaudio {
         :enabled true
         :command "pactl list short sinks | grep -E '\\bRUNNING$'"
         :tasks   { :sleep true } }

      :video {
         :enabled true
         :command "pgrep -l '^(celluloid|hypnotix|skypeforlinux|teams|vlc|zoom)$'"
         :tasks   { :dpms  true
                    :sleep true } }

      :zfs-scrub {
         :enabled true
         :command "zpool status | grep -E '(resilver|scrub) in progress'"
         :tasks   { :sleep true } }
   }
}
```

### System specifications:

**Operating system:** Linux Mint Cinnamon 20.2.

**Kernel:** 5.11.0-25

### Additional information:

I do not use `PulseAudio`, I use `Pipewire` instead, which I do not know if it is supported or not. Also, I use EasyEffects which is the new successor of PulseEffects.

**Comment by mzuther** [comment]
You seem to be one of MoccaFaux' first users, welcome! 😄 

You are right, the problem is that you don't use PulseAudio. It has a nice feature that allows me to check whether audio is playing, and so I don't have to add all of the players to my `config.edn`. Also, clementine might have changed its (internal) name.

What happens when you run the followin line on your terminal when Clementine is open?

    pgrep -l clementine

**Comment by Ahmed-E-86** [comment]
> pgrep -l clementine

```
4708 clementine
4736 clementine-tagr
4737 clementine-tagr
4738 clementine-tagr
4739 clementine-tagr
```

**Comment by Ahmed-E-86** [comment]
> You seem to be one of MoccaFaux' first users, welcome! smile

Thanks! I am glad that I found it.

> You are right, the problem is that you don't use PulseAudio. It has a nice feature that allows me to check whether audio is playing, and so I don't have to add all of the players to my config.edn.

I can not go back to PulseAudio, because Pipewire runs so much better on my machine.


> Also, clementine might have changed its (internal) name. What happens when you run the followin line on your terminal when Clementine is open?
> 
> `pgrep -l clementine`

```
4708 clementine
4736 clementine-tagr
4737 clementine-tagr
4738 clementine-tagr
4739 clementine-tagr
```

That is the output of the command you use for PulseAudio when using Pipewire

`pactl list short sinks | grep -E 'RUNNING'`

```
44	alsa_output.pci-0000_00_1b.0.analog-stereo	PipeWire	s32le 2ch 48000Hz	RUNNING
57	easyeffects_sink	PipeWire	float32le 2ch 48000Hz	RUNNING
```

I do not understand why using //s, //b, ^, and $ in the middle of bash commands.

**Comment by mzuther** [comment]
Sorry for keeping you waiting...

The output of `pgrep -l clementine` looks fine to me. Also, you said that MoccaFaux's icon turns to green, which means that it detects Clementine - and so you don't have do worry about using PulseAudio.

I suspect something different: you have to turn off your desktop's power management (Gnome, KDE, ...). That is, if you don't run MoccaFaux, your laptop should neither turn off the screen, nor go to sleep on its own. Did you do that? You can simply check by waiting. :smile: 

Also, you need to have `xautolock` and `xset` installed. When you open the console, what is the output of `whereis xautolock` and `whereis xset`?

This information should be in the manual, so I'll have to update it.

> I do not understand why using //s, //b, ^, and $ in the middle of bash commands.

These are [regular expressions](https://www.regular-expressions.info/quickstart.html). While not necessary, they prevent pgrep (and thus MoccaFaux) from finding applications that have a similar name. For example, `pgrep -l 'clementine'` gives this list:

```
43766 clementine
43779 clementine-tagr
43780 clementine-tagr
[and so on]

```

but `pgrep -l '^clementine$'` finds only the main app:

```
43766 clementine
```
As a side note, you have to use double backslashes `\\s` instead of single ones `\s` because your shell removes the second one.

**Comment by Ahmed-E-86** [comment]
> Also, you need to have xautolock and xset installed. When you open the console, what is the output of whereis xautolock and whereis xset?

`xautolock` was not installed, but xset was installed as a part of `x11-xserver-utils`

They both can be installed on any Ubuntu-based Linux distro like this:

```
sudo apt install x11-xserver-utils xautolock
```
That will be useful for the documentation.

It should work fine now, I will give it another try.

**Comment by Ahmed-E-86** [comment]
The system-tray icon of the applications turns to green when there is any application playing music, whatever it is in the audio list or not, but it still does not inhibit power management at all.

I use Linux Mint Cinnamon 20.2.

**Comment by mzuther** [comment]
> ```
> sudo apt install x11-xserver-utils xautolock
> ```

Thanks for the command!

Did you disable power management in Cinnamon? It's easy to test: don't run MoccaFaux (stopping it might not work) and see if your laptop goes to sleep. I think that your problem lies in that direction.

If this doesn't work, try running MoccaFaux from the command line:

```
java -jar moccafaux.jar
```
This will display additional information on what MoccaFaux does, maybe this helps.

Good luck! :smile:

**Comment by Ahmed-E-86** [comment]
> Did you disable power management in Cinnamon? It's easy to test: don't run MoccaFaux (stopping it might not work) and see if your laptop goes to sleep. I think that your problem lies in that direction.

I do not know what do you mean. MoccaFaux inhibit power management, or does it work the opposite way?

> If this doesn't work, try running MoccaFaux from the command line:
> 
> java -jar moccafaux.jar

```
o------------------------------------------------------------------------------o
|                               MoccaFaux v1.4.1                               |
o------------------------------------------------------------------------------o

[21:44:19]  Probe:    every 60 seconds
            Traybar:  true

            Tasks:    - dpms
                      - sleep

            Watches:  - audio
                      - important-processes
                      - pulseaudio
                      - video
                      - zfs-scrub

--------------------------------------------------------------------------------

[21:44:20]  Task:     dpms
            State:    active -> allow screen to save energy
            Command:  xset dpms 0 600 900
            Result:   success

[21:44:20]  Task:     sleep
            State:    idle -> keep computer awake
            Command:  xautolock -exit
            Result:   failed

--------------------------------------------------------------------------------
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000840062040 (file:/mnt/Linux/moccafaux-1.4.1.jar) to method sun.awt.SunToolkit.getImage(java.net.URL)
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000840062040
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by mzuther** [comment]
> I do not know what do you mean. MoccaFaux inhibit power management, or does it work the opposite way?

This is not true and I should probably clarify this in the Readme file. I use a desktop environment (i3) without power management, which is why I wrote MoccaFaux, but most other desktops (like Cinnamon) come with their own power management. I'm currently on i3, but I'll log out and send you instructions in a minute or so...

> WARNING: An illegal reflective access operation has occurred

I'll have to fix these warnings one day, but they are not relevant for the problem.

**Comment by mzuther** [comment]
The easiest way to open Cinnamon's power management options is from your console:

```
cinnamon-settings power
```

Then change your "Power Options" like this:

![cinnamon-power](https://user-images.githubusercontent.com/316423/130866515-e3d2e9ce-686f-4fe2-919c-c46c126b4050.png)

**Comment by Ahmed-E-86** [comment]
I know how to turn off power settings, I just did not know how MoccaFaux works, but I do now.

It suspends the machine when certain conditions are not met, otherwise, it will keep the machine awake.

I thought that the application inhibits power management when certain conditions are met, otherwise, the machine will be suspended, and that is not how it works, and I am a little disappointed.

Anyway, thanks for your help. The application works fine, but you need to update the documentation.

**Comment by mzuther** [comment]
I have updated the documentation and released a new version of MoccaFaux. Changing the config file and debugging problems is now much easier.

> I thought that the application inhibits power management when certain conditions are met, otherwise, the machine will be suspended, [...]

I do not have enough information on what you want to achieve, but the two situations I can think of can be handled by MoccaFaux.

Do you want to disable Cinnamon's own power management when certain applications run? You need to find a way that programmatically tells Cinnamon to disable power management - a few lines of Python script that send a D-Bus message might be enough. Then just call this script from a MoccaFaux task.

Do you want to manually start MoccaFaux in order to automatically shut down your computer when an application has finished doing its job? This is also possible (call the command `systemctl suspend` from a task), but you probably have to change user rights - in many systems, only the superuser can execute this command.

**Comment by Ahmed-E-86** [comment]
> I have updated the documentation and released a new version of MoccaFaux. Changing the config file and debugging problems is now much easier.

Great! I saw the new documentation earlier today.

> Do you want to disable Cinnamon's own power management when certain applications run? You need to find a way that programmatically tells Cinnamon to disable power management - a few lines of Python script that send a D-Bus message might be enough. Then just call this script from a MoccaFaux task.

When a program like VLC is playing a video, it tells the system to keep the screen on, and to inhibit the system from being suspended. I do not know if it can be done by executing a command.

**Comment by mzuther** [comment]
On reading your answer, I updated the documentation yet again:

> ## Motivation
>
> To be honest, controlling screensaver and power management of Linux
> desktops is quite a mess. Despite some conventions, there seems to be
> no universal standard, and applications and tools often resort to
> kludges.
> 
> I wanted to keep my computer awake when syncing large files, but there
> seemed to be no solution that would survive the ravages of time. So I
> decided that disabling power management and screensaver was my best
> option and started to write **MoccaFaux**.

Your best option might be to simulate keypresses using `xdotool`: https://stackoverflow.com/a/11593533

Or do it my way and use MoccaFaux as a replacement for power management and screensaver... :smile:
